---

- hosts: etcd
  roles:
    - etcd

- hosts: all-k8s-nodes
  roles:
    - kubernetes-common

- hosts: kube-master
  roles:
    - kubernetes-master

- hosts: kube-nodes
  roles:
    - kubernetes-nodes
