---

# Here we initialise the cluster with Kubeadm. We add the token manually so that we
# know its value when we initialise our nodes. We add --api-advertise-addresses manually
# because by default Kubeadm would choose the nat IP we get from Virtualbox, which is not good.
- name:    Initialise Kubernetes Cluster
  become:  true
  shell:   kubeadm init --token="{{ kubeadm_token }}" --api-advertise-addresses="{{ inventory_hostname }}" --external-etcd-endpoints="{{ etcd_endpoint }}"

- name: Copy Calico Config
  become: true
  template:
    src:  "calico.yaml.j2"
    dest: "/home/vagrant/calico.yaml"

- name:    Install Calico
  become:  true
  shell:   kubectl apply -f /home/vagrant/calico.yaml
